export enum UserRole {
  PET_PARENT = 'PET_PARENT',
  PROVIDER = 'PROVIDER',
  SERVICE_PROVIDER = 'SERVICE_PROVIDER',
  RESCUE_PARTNER = 'RESCUE_PARTNER',
  VAN_WORKER = 'VAN_WORKER',
  ADMIN = 'ADMIN',
}

export const USER_ROLES = Object.values(UserRole);
